import { copyObject, listObjects } from "@/lib/storage/operations";

export interface ImageMigrationResult {
	/** S3 keys that were successfully copied (for rollback). */
	copiedKeys: string[];
	/** Source -> destination mapping actually performed. */
	mappings: { from: string; to: string }[];
}

/**
 * Copy every object under `images/workshopProblems/{workshopProblemId}/` to
 * `images/problems/{publishedProblemId}/{same-basename}`. Returns the list of
 * destination keys for rollback.
 */
export async function migrateWorkshopImages(
	workshopProblemId: number,
	publishedProblemId: number
): Promise<ImageMigrationResult> {
	const srcPrefix = `images/workshopProblems/${workshopProblemId}/`;
	const dstPrefix = `images/problems/${publishedProblemId}/`;
	const sources = await listObjects(srcPrefix);

	const copiedKeys: string[] = [];
	const mappings: { from: string; to: string }[] = [];

	for (const from of sources) {
		const basename = from.slice(srcPrefix.length);
		if (!basename) continue; // skip the folder marker if any
		const to = `${dstPrefix}${basename}`;
		await copyObject(from, to);
		copiedKeys.push(to);
		mappings.push({ from, to });
	}

	return { copiedKeys, mappings };
}

/**
 * Rewrite a markdown string so all references to the workshop image namespace
 * become references to the published problem image namespace.
 *
 * Handles both forms:
 *  1. Raw path: `images/workshopProblems/{id}/{file}`
 *  2. API-encoded URL: `/api/images/images%2FworkshopProblems%2F{id}%2F{file}`
 *     (generated by getImageUrl(generateWorkshopProblemImagePath(...)))
 */
export function rewriteWorkshopImageUrls(
	markdown: string,
	workshopProblemId: number,
	publishedProblemId: number
): string {
	const rawFrom = `images/workshopProblems/${workshopProblemId}/`;
	const rawTo = `images/problems/${publishedProblemId}/`;

	const encFrom = `images%2FworkshopProblems%2F${workshopProblemId}%2F`;
	const encTo = `images%2Fproblems%2F${publishedProblemId}%2F`;

	return markdown.replaceAll(rawFrom, rawTo).replaceAll(encFrom, encTo);
}
